problem1: problem1.o
	g++ problem1.o -o problem1

problem2: problem2.o
	g++ problem2.o -o problem2 -g

problem3: problem3.o
	g++ problem3.o -o problem3

problem4: problem4.o
	g++ problem4.o -o problem4

problem5: problem5.o
	g++ problem5.o -o problem5

clean: 
	rm -rf *.o problem1 problem2 problem3 problem4 problem5


