problem2 : problem2.cpp
	g++ -o problem2 problem2.cpp

problem3 : problem3.cpp
	g++ -o problem3 problem3.cpp

problem4 : problem4.cpp
	g++ -o problem4 problem4.cpp

problem5 : problem5.cpp
	g++ -o problem5 problem5.cpp

clean : 
	rm -rf problem2 problem3 problem4 problem5

