problem1 : problem1.o
	g++ -o problem1 problem1.o

problem1.o : problem1.cpp animal.h
	g++ -c problem1.cpp

problem4 : problem4.o
	g++ -o problem4 problem4.o

prroblem4.o : problem4.cpp
	g++ -c problem4.cpp

clean : 
	rm -rf *.o problem1 problem4
