problem1 : problem1.cpp
	g++ -o problem1 problem1.cpp

problem2 : problem2.cpp
	g++ -o problem2 problem2.cpp

problem3 : problem3.cpp
	g++ -o problem3 problem3.cpp

problem4 : problem4.cpp
	g++ -o problem4 problem4.cpp

clean :
	rm -rf *.o  problem1 problem2 problem3 problem4
